# Site settings
title: deaktator
# email: r.m.deak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stats, programming wisdom, general insight
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://deaktator.github.io" # the base hostname & protocol for your site
twitter_username: deaktator
github_username:  deaktator

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
#  syntax_highlighter: rouge

gist:
  noscript: false

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
